name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH_REFERENCE=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH_REFERENCE }}
          key: ${{ runner.os }}-pnpm-store-reference-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-reference-
      - name: build reference
        run: |
          pnpm install && pnpm build
          tar -zcvf res.tar.gz -C ./dist/ .
      - name: scp dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ref.alomerry.com
          username: root
          key: ${{ secrets.VPS_SECRET_SSH_KEY }}
          port: 22
          source: "res.tar.gz"
          target: "/tmp/"
      - name: deploy reference
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ref.alomerry.com
          username: root
          key: ${{ secrets.VPS_SECRET_SSH_KEY }}
          port: 22
          script: |
            rm -rf /root/apps/nginx/site/ref.alomerry.com/*
            tar -zxvf /tmp/res.tar.gz -C /root/apps/nginx/site/ref.alomerry.com/;
            rm /tmp/res.tar.gz

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: dist
      #     path: ${{ github.workspace }}\dist\**\*
